"""
Code-builder blueprints. Each blueprint IS a code-building bot:
given a (prompt, name) it emits a folder of real, runnable files.

Output shape (per blueprint):
{
  "bot": {                       # the bot that builds this app
    "name": str,
    "domain": str,
    "recipe": [str],             # ordered steps the bot performs
    "templates": [str],          # file paths the bot owns
  },
  "app": {                       # the produced app
    "name": str,
    "version": "0.1.0",
    "tagline": str,
    "entities": [{"name": str, "fields": [{"name": str, "type": str}]}],
    "endpoints": [{"method": str, "path": str, "purpose": str}],
    "stack": [str],
  },
  "files": [{"path": str, "content": str}],
}
"""
from __future__ import annotations

import hashlib
import re
from typing import Callable


def _slug(text: str, fallback: str = "app") -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "-", text.strip().lower()).strip("-")
    return s or fallback


def _name_from_prompt(prompt: str, fallback: str = "app") -> str:
    toks = re.findall(r"[A-Za-z]+", prompt)
    return ("".join(t.capitalize() for t in toks[:3]) or fallback) or fallback


# ----------------------------------------------------------------------------
# Shared file fragments
# ----------------------------------------------------------------------------
def _readme(name: str, tagline: str, run_lines: list[str]) -> str:
    runs = "\n".join(f"   {ln}" for ln in run_lines)
    return f"""# {name}

> {tagline}

Generated by RECURSIVE.BBS.

## Run it

```bash
{runs}
```

Open http://localhost:8000 in your browser.

## Structure

- `backend/server.py` — FastAPI app, in-memory storage (swap to MongoDB later)
- `backend/requirements.txt` — Python deps
- `frontend/index.html` — single-page UI (vanilla JS, no build step)
- `run.sh` — one-shot installer + launcher

## Endpoints

See the OpenAPI docs at http://localhost:8000/docs once running.
"""


def _requirements_txt() -> str:
    return "fastapi==0.115.0\nuvicorn[standard]==0.30.6\npydantic==2.9.2\n"


def _run_sh() -> str:
    return """#!/usr/bin/env bash
set -e
cd "$(dirname "$0")"
python3 -m venv .venv 2>/dev/null || true
source .venv/bin/activate
pip install -q -r backend/requirements.txt
cd backend
exec uvicorn server:app --host 0.0.0.0 --port 8000
"""


def _server_preamble(title: str) -> str:
    return f'''"""
{title} — generated by RECURSIVE.BBS.
FastAPI + in-memory storage. Swap the `_db` dict for MongoDB when you are ready.
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

app = FastAPI(title="{title}")
_db: dict = {{}}

FRONTEND = Path(__file__).resolve().parent.parent / "frontend"
'''


def _server_footer() -> str:
    return '''

# ---- static frontend -------------------------------------------------------
if FRONTEND.exists():
    app.mount("/static", StaticFiles(directory=str(FRONTEND)), name="static")

    @app.get("/")
    def index():
        return FileResponse(FRONTEND / "index.html")
'''


def _html(title: str, body_html: str, script_js: str) -> str:
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
  :root {{ --bg:#0e0f12; --fg:#e6e7eb; --mut:#8a8e98; --acc:#7cffb2; --acc2:#ff79c6; --line:#1f2128; }}
  *{{box-sizing:border-box}}
  body{{margin:0;font:14px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;background:var(--bg);color:var(--fg)}}
  header{{padding:18px 24px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}}
  header h1{{margin:0;font-size:18px;letter-spacing:.1em;text-transform:uppercase;color:var(--acc)}}
  main{{padding:24px;max-width:1100px;margin:0 auto}}
  button{{background:transparent;color:var(--acc);border:1px solid var(--acc);padding:6px 12px;cursor:pointer;font:inherit}}
  button:hover{{background:var(--acc);color:#000}}
  input,textarea,select{{background:#15171c;color:var(--fg);border:1px solid var(--line);padding:8px;font:inherit;width:100%}}
  .row{{display:flex;gap:12px;flex-wrap:wrap}}
  .card{{background:#15171c;border:1px solid var(--line);padding:12px;margin:8px 0}}
  .muted{{color:var(--mut)}}
  .pill{{display:inline-block;padding:2px 8px;border:1px solid var(--acc2);color:var(--acc2);font-size:11px;letter-spacing:.1em;text-transform:uppercase}}
  .grid{{display:grid;gap:16px}}
</style>
</head>
<body>
<header><h1>{title}</h1><span class="pill">recursive.bbs build</span></header>
<main>
{body_html}
</main>
<script>
const API = "";  // same-origin
{script_js}
</script>
</body>
</html>
"""


# ----------------------------------------------------------------------------
# Blueprint: Kanban
# ----------------------------------------------------------------------------
def blueprint_kanban(prompt: str) -> dict:
    name = _name_from_prompt(prompt, "KanbanApp")
    slug = _slug(name, "kanban")
    server_py = _server_preamble(name) + '''
# ---- models ----------------------------------------------------------------
class Card(BaseModel):
    id: str = Field(default_factory=lambda: uuid.uuid4().hex)
    column_id: str
    title: str
    description: str = ""
    position: int = 0
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

class Column(BaseModel):
    id: str = Field(default_factory=lambda: uuid.uuid4().hex)
    board_id: str
    title: str
    position: int = 0

class Board(BaseModel):
    id: str = Field(default_factory=lambda: uuid.uuid4().hex)
    title: str
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

class MoveReq(BaseModel):
    column_id: str
    position: int

_db.setdefault("boards", {})
_db.setdefault("columns", {})
_db.setdefault("cards", {})

# ---- bootstrap a demo board on first run -----------------------------------
def _bootstrap():
    if _db["boards"]:
        return
    b = Board(title="Demo Board"); _db["boards"][b.id] = b.model_dump()
    cols = []
    for i, t in enumerate(["TODO", "DOING", "DONE"]):
        c = Column(board_id=b.id, title=t, position=i)
        _db["columns"][c.id] = c.model_dump()
        cols.append(c)
    for i, t in enumerate(["Set up repo", "Write tests", "Ship MVP"]):
        card = Card(column_id=cols[i].id, title=t, position=0)
        _db["cards"][card.id] = card.model_dump()
_bootstrap()

# ---- endpoints -------------------------------------------------------------
@app.get("/api/boards")
def list_boards(): return list(_db["boards"].values())

@app.post("/api/boards")
def create_board(b: Board):
    _db["boards"][b.id] = b.model_dump(); return b

@app.get("/api/boards/{board_id}/columns")
def list_columns(board_id: str):
    cols = [c for c in _db["columns"].values() if c["board_id"] == board_id]
    return sorted(cols, key=lambda c: c["position"])

@app.post("/api/columns")
def create_column(c: Column):
    if c.board_id not in _db["boards"]: raise HTTPException(404, "board not found")
    _db["columns"][c.id] = c.model_dump(); return c

@app.get("/api/columns/{column_id}/cards")
def list_cards(column_id: str):
    cards = [c for c in _db["cards"].values() if c["column_id"] == column_id]
    return sorted(cards, key=lambda c: c["position"])

@app.post("/api/cards")
def create_card(c: Card):
    if c.column_id not in _db["columns"]: raise HTTPException(404, "column not found")
    _db["cards"][c.id] = c.model_dump(); return c

@app.patch("/api/cards/{card_id}/move")
def move_card(card_id: str, req: MoveReq):
    if card_id not in _db["cards"]: raise HTTPException(404, "card not found")
    if req.column_id not in _db["columns"]: raise HTTPException(404, "column not found")
    card = _db["cards"][card_id]
    card["column_id"] = req.column_id
    card["position"] = req.position
    return card

@app.delete("/api/cards/{card_id}")
def delete_card(card_id: str):
    _db["cards"].pop(card_id, None); return {"ok": True}
''' + _server_footer()

    body = """
<div class="row" style="gap:16px;margin-bottom:18px">
  <div><span class="muted">board:</span> <strong id="board-name">…</strong></div>
  <button id="add-col-btn">+ column</button>
</div>
<div id="board" class="grid" style="grid-template-columns:repeat(auto-fill,minmax(240px,1fr))"></div>
"""
    script = r"""
let BOARD_ID = null;

async function loadBoard() {
  const boards = await fetch(API+"/api/boards").then(r=>r.json());
  const b = boards[0];
  BOARD_ID = b.id;
  document.getElementById("board-name").textContent = b.title;
  const cols = await fetch(API+`/api/boards/${BOARD_ID}/columns`).then(r=>r.json());
  const root = document.getElementById("board"); root.innerHTML = "";
  for (const col of cols) {
    const el = document.createElement("div");
    el.className = "card"; el.dataset.colId = col.id;
    el.innerHTML = `
      <div class="row" style="justify-content:space-between;align-items:center;margin-bottom:8px">
        <strong style="color:var(--acc)">${col.title}</strong>
        <button class="add-card">+ card</button>
      </div>
      <div class="cards"></div>`;
    el.addEventListener("dragover", e => e.preventDefault());
    el.addEventListener("drop", async e => {
      e.preventDefault();
      const cardId = e.dataTransfer.getData("text/plain");
      await fetch(API+`/api/cards/${cardId}/move`, {
        method: "PATCH",
        headers: {"Content-Type":"application/json"},
        body: JSON.stringify({column_id: col.id, position: 0}),
      });
      loadBoard();
    });
    el.querySelector(".add-card").onclick = async () => {
      const title = prompt("card title?");
      if (!title) return;
      await fetch(API+"/api/cards", {
        method:"POST",
        headers:{"Content-Type":"application/json"},
        body: JSON.stringify({column_id: col.id, title}),
      });
      loadBoard();
    };
    const cardList = el.querySelector(".cards");
    const cards = await fetch(API+`/api/columns/${col.id}/cards`).then(r=>r.json());
    for (const c of cards) {
      const cd = document.createElement("div");
      cd.className = "card"; cd.style.cursor = "grab"; cd.draggable = true;
      cd.textContent = c.title;
      cd.addEventListener("dragstart", e => e.dataTransfer.setData("text/plain", c.id));
      cardList.appendChild(cd);
    }
    root.appendChild(el);
  }
}

document.getElementById("add-col-btn").onclick = async () => {
  const title = prompt("column title?");
  if (!title) return;
  await fetch(API+"/api/columns", {
    method:"POST",
    headers:{"Content-Type":"application/json"},
    body: JSON.stringify({board_id: BOARD_ID, title, position: 99}),
  });
  loadBoard();
};

loadBoard();
"""
    files = [
        {"path": "backend/server.py", "content": server_py},
        {"path": "backend/requirements.txt", "content": _requirements_txt()},
        {"path": "frontend/index.html", "content": _html(name, body, script)},
        {"path": "run.sh", "content": _run_sh()},
        {"path": "README.md", "content": _readme(name, "a kanban board with drag-and-drop cards", ["bash run.sh"])},
    ]
    return {
        "bot": {
            "name": f"{slug}.builder.v1",
            "domain": "kanban",
            "recipe": [
                "detect-domain(kanban)",
                "scaffold(fastapi+inmem)",
                "emit(Board,Column,Card models)",
                "emit(/api/cards/{id}/move endpoint)",
                "compose(html5-dragdrop frontend)",
                "seed(demo board with 3 columns)",
            ],
            "templates": [f["path"] for f in files],
        },
        "app": {
            "name": name,
            "version": "0.1.0",
            "tagline": "a kanban board with drag-and-drop cards",
            "entities": [
                {"name": "Board", "fields": [{"name":"id","type":"str"},{"name":"title","type":"str"},{"name":"created_at","type":"datetime"}]},
                {"name": "Column", "fields": [{"name":"id","type":"str"},{"name":"board_id","type":"str"},{"name":"title","type":"str"},{"name":"position","type":"int"}]},
                {"name": "Card", "fields": [{"name":"id","type":"str"},{"name":"column_id","type":"str"},{"name":"title","type":"str"},{"name":"description","type":"str"},{"name":"position","type":"int"}]},
            ],
            "endpoints": [
                {"method":"GET","path":"/api/boards","purpose":"list boards"},
                {"method":"POST","path":"/api/boards","purpose":"create board"},
                {"method":"GET","path":"/api/boards/{id}/columns","purpose":"list columns of a board"},
                {"method":"POST","path":"/api/columns","purpose":"create column"},
                {"method":"GET","path":"/api/columns/{id}/cards","purpose":"list cards in column"},
                {"method":"POST","path":"/api/cards","purpose":"create card"},
                {"method":"PATCH","path":"/api/cards/{id}/move","purpose":"drag-drop reorder"},
                {"method":"DELETE","path":"/api/cards/{id}","purpose":"delete card"},
            ],
            "stack": ["FastAPI", "Pydantic v2", "vanilla JS", "HTML5 drag-and-drop"],
        },
        "files": files,
    }


# ----------------------------------------------------------------------------
# Blueprint: Notes
# ----------------------------------------------------------------------------
def blueprint_notes(prompt: str) -> dict:
    name = _name_from_prompt(prompt, "NotesApp")
    slug = _slug(name, "notes")
    server_py = _server_preamble(name) + '''
class Note(BaseModel):
    id: str = Field(default_factory=lambda: uuid.uuid4().hex)
    title: str
    body: str = ""
    tags: list[str] = []
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

_db.setdefault("notes", {})

@app.get("/api/notes")
def list_notes(tag: Optional[str] = None):
    notes = list(_db["notes"].values())
    if tag:
        notes = [n for n in notes if tag in n.get("tags", [])]
    return sorted(notes, key=lambda n: n["updated_at"], reverse=True)

@app.post("/api/notes")
def create_note(n: Note):
    _db["notes"][n.id] = n.model_dump(); return n

@app.get("/api/notes/{note_id}")
def get_note(note_id: str):
    if note_id not in _db["notes"]: raise HTTPException(404, "note not found")
    return _db["notes"][note_id]

@app.patch("/api/notes/{note_id}")
def update_note(note_id: str, n: Note):
    if note_id not in _db["notes"]: raise HTTPException(404, "note not found")
    data = n.model_dump(); data["id"] = note_id
    data["updated_at"] = datetime.now(timezone.utc)
    _db["notes"][note_id] = data; return data

@app.delete("/api/notes/{note_id}")
def delete_note(note_id: str):
    _db["notes"].pop(note_id, None); return {"ok": True}

@app.get("/api/tags")
def list_tags():
    tags = set()
    for n in _db["notes"].values():
        tags.update(n.get("tags", []))
    return sorted(tags)
''' + _server_footer()

    body = """
<div class="row" style="margin-bottom:16px;gap:8px">
  <input id="filter" placeholder="filter by tag…" style="max-width:240px">
  <button id="new-btn">+ new note</button>
</div>
<div class="grid" style="grid-template-columns:1fr 2fr">
  <div id="list"></div>
  <div id="editor" class="card"><em class="muted">select or create a note</em></div>
</div>
"""
    script = r"""
let CURRENT = null;
async function loadList() {
  const tag = document.getElementById("filter").value.trim();
  const url = tag ? `${API}/api/notes?tag=${encodeURIComponent(tag)}` : `${API}/api/notes`;
  const notes = await fetch(url).then(r=>r.json());
  const list = document.getElementById("list"); list.innerHTML = "";
  for (const n of notes) {
    const el = document.createElement("div");
    el.className = "card"; el.style.cursor = "pointer";
    el.innerHTML = `<strong>${n.title||"(untitled)"}</strong><div class="muted" style="font-size:11px">${(n.tags||[]).map(t=>"#"+t).join(" ")}</div>`;
    el.onclick = () => openNote(n.id);
    list.appendChild(el);
  }
}
async function openNote(id) {
  const n = await fetch(API+`/api/notes/${id}`).then(r=>r.json());
  CURRENT = n;
  document.getElementById("editor").innerHTML = `
    <input id="t" value="${n.title.replace(/"/g,'&quot;')}" style="margin-bottom:8px">
    <input id="tags" placeholder="tags, comma separated" value="${(n.tags||[]).join(', ')}" style="margin-bottom:8px">
    <textarea id="b" rows="14">${n.body||""}</textarea>
    <div class="row" style="margin-top:8px"><button id="save">save</button><button id="del" style="border-color:#ff5555;color:#ff5555">delete</button></div>`;
  document.getElementById("save").onclick = save;
  document.getElementById("del").onclick = del;
}
async function save() {
  const title = document.getElementById("t").value;
  const body = document.getElementById("b").value;
  const tags = document.getElementById("tags").value.split(",").map(s=>s.trim()).filter(Boolean);
  await fetch(API+`/api/notes/${CURRENT.id}`, {
    method:"PATCH", headers:{"Content-Type":"application/json"},
    body: JSON.stringify({title, body, tags}),
  });
  loadList();
}
async function del() {
  if (!confirm("delete this note?")) return;
  await fetch(API+`/api/notes/${CURRENT.id}`, {method:"DELETE"});
  CURRENT = null;
  document.getElementById("editor").innerHTML = '<em class="muted">select or create a note</em>';
  loadList();
}
document.getElementById("new-btn").onclick = async () => {
  const r = await fetch(API+"/api/notes", {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:"new note"})});
  const n = await r.json(); openNote(n.id); loadList();
};
document.getElementById("filter").oninput = loadList;
loadList();
"""
    files = [
        {"path": "backend/server.py", "content": server_py},
        {"path": "backend/requirements.txt", "content": _requirements_txt()},
        {"path": "frontend/index.html", "content": _html(name, body, script)},
        {"path": "run.sh", "content": _run_sh()},
        {"path": "README.md", "content": _readme(name, "a tag-filtered notes app", ["bash run.sh"])},
    ]
    return {
        "bot": {
            "name": f"{slug}.builder.v1",
            "domain": "notes",
            "recipe": [
                "detect-domain(notes)",
                "scaffold(fastapi+inmem)",
                "emit(Note model with tags)",
                "emit(CRUD + tag filter)",
                "compose(list/editor UI)",
            ],
            "templates": [f["path"] for f in files],
        },
        "app": {
            "name": name,
            "version": "0.1.0",
            "tagline": "a tag-filtered notes app",
            "entities": [
                {"name":"Note","fields":[
                    {"name":"id","type":"str"},{"name":"title","type":"str"},
                    {"name":"body","type":"str"},{"name":"tags","type":"list[str]"},
                    {"name":"created_at","type":"datetime"},{"name":"updated_at","type":"datetime"},
                ]},
            ],
            "endpoints": [
                {"method":"GET","path":"/api/notes","purpose":"list (filter by ?tag=)"},
                {"method":"POST","path":"/api/notes","purpose":"create"},
                {"method":"GET","path":"/api/notes/{id}","purpose":"read"},
                {"method":"PATCH","path":"/api/notes/{id}","purpose":"update"},
                {"method":"DELETE","path":"/api/notes/{id}","purpose":"delete"},
                {"method":"GET","path":"/api/tags","purpose":"list known tags"},
            ],
            "stack": ["FastAPI", "Pydantic v2", "vanilla JS"],
        },
        "files": files,
    }


# ----------------------------------------------------------------------------
# Blueprint: Habit Tracker
# ----------------------------------------------------------------------------
def blueprint_habits(prompt: str) -> dict:
    name = _name_from_prompt(prompt, "HabitApp")
    slug = _slug(name, "habits")
    server_py = _server_preamble(name) + '''
from datetime import date

class Habit(BaseModel):
    id: str = Field(default_factory=lambda: uuid.uuid4().hex)
    name: str
    target_per_week: int = 7
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

class Entry(BaseModel):
    id: str = Field(default_factory=lambda: uuid.uuid4().hex)
    habit_id: str
    date: str   # YYYY-MM-DD
    done: bool = True

_db.setdefault("habits", {})
_db.setdefault("entries", {})

@app.get("/api/habits")
def list_habits():
    out = []
    for h in _db["habits"].values():
        entries = [e for e in _db["entries"].values() if e["habit_id"] == h["id"] and e.get("done")]
        # streak: count consecutive days backward from today
        days = sorted({e["date"] for e in entries}, reverse=True)
        streak = 0
        today = date.today()
        for i, d in enumerate(days):
            expected = (today.toordinal() - i)
            if date.fromisoformat(d).toordinal() == expected:
                streak += 1
            else:
                break
        out.append({**h, "total_done": len(entries), "streak": streak})
    return out

@app.post("/api/habits")
def create_habit(h: Habit):
    _db["habits"][h.id] = h.model_dump(); return h

@app.delete("/api/habits/{habit_id}")
def delete_habit(habit_id: str):
    _db["habits"].pop(habit_id, None)
    for eid in [e["id"] for e in _db["entries"].values() if e["habit_id"] == habit_id]:
        _db["entries"].pop(eid, None)
    return {"ok": True}

@app.post("/api/habits/{habit_id}/check")
def check_today(habit_id: str):
    if habit_id not in _db["habits"]: raise HTTPException(404, "habit not found")
    today = date.today().isoformat()
    existing = next((e for e in _db["entries"].values() if e["habit_id"] == habit_id and e["date"] == today), None)
    if existing:
        existing["done"] = not existing["done"]
        return existing
    e = Entry(habit_id=habit_id, date=today, done=True)
    _db["entries"][e.id] = e.model_dump(); return e
''' + _server_footer()

    body = """
<div class="row" style="margin-bottom:16px;gap:8px">
  <input id="new-name" placeholder="new habit (e.g. 'read 20 pages')" style="max-width:320px">
  <button id="add-btn">+ add</button>
</div>
<div id="list" class="grid" style="grid-template-columns:repeat(auto-fill,minmax(240px,1fr))"></div>
"""
    script = r"""
async function load() {
  const habits = await fetch(API+"/api/habits").then(r=>r.json());
  const list = document.getElementById("list"); list.innerHTML = "";
  if (!habits.length) { list.innerHTML = '<em class="muted">no habits yet — add one above</em>'; return; }
  for (const h of habits) {
    const el = document.createElement("div");
    el.className = "card";
    el.innerHTML = `
      <div class="row" style="justify-content:space-between;align-items:center">
        <strong>${h.name}</strong>
        <span class="pill">streak ${h.streak}🔥</span>
      </div>
      <div class="muted" style="font-size:12px;margin:6px 0">total done: ${h.total_done}</div>
      <div class="row"><button class="check">check today</button><button class="del" style="border-color:#ff5555;color:#ff5555">delete</button></div>`;
    el.querySelector(".check").onclick = async () => {
      await fetch(API+`/api/habits/${h.id}/check`, {method:"POST"}); load();
    };
    el.querySelector(".del").onclick = async () => {
      if (!confirm("delete this habit?")) return;
      await fetch(API+`/api/habits/${h.id}`, {method:"DELETE"}); load();
    };
    document.getElementById("list").appendChild(el);
  }
}
document.getElementById("add-btn").onclick = async () => {
  const name = document.getElementById("new-name").value.trim();
  if (!name) return;
  await fetch(API+"/api/habits", {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name})});
  document.getElementById("new-name").value = ""; load();
};
load();
"""
    files = [
        {"path": "backend/server.py", "content": server_py},
        {"path": "backend/requirements.txt", "content": _requirements_txt()},
        {"path": "frontend/index.html", "content": _html(name, body, script)},
        {"path": "run.sh", "content": _run_sh()},
        {"path": "README.md", "content": _readme(name, "habit tracker with streak counter", ["bash run.sh"])},
    ]
    return {
        "bot": {
            "name": f"{slug}.builder.v1",
            "domain": "habit-tracker",
            "recipe": [
                "detect-domain(habit-tracker)",
                "scaffold(fastapi+inmem)",
                "emit(Habit,Entry models)",
                "emit(streak calculator)",
                "emit(check-today toggle)",
            ],
            "templates": [f["path"] for f in files],
        },
        "app": {
            "name": name,
            "version": "0.1.0",
            "tagline": "habit tracker with streak counter",
            "entities": [
                {"name":"Habit","fields":[{"name":"id","type":"str"},{"name":"name","type":"str"},{"name":"target_per_week","type":"int"}]},
                {"name":"Entry","fields":[{"name":"id","type":"str"},{"name":"habit_id","type":"str"},{"name":"date","type":"str"},{"name":"done","type":"bool"}]},
            ],
            "endpoints": [
                {"method":"GET","path":"/api/habits","purpose":"list (with streak,total_done)"},
                {"method":"POST","path":"/api/habits","purpose":"create habit"},
                {"method":"DELETE","path":"/api/habits/{id}","purpose":"delete habit + entries"},
                {"method":"POST","path":"/api/habits/{id}/check","purpose":"toggle today's entry"},
            ],
            "stack": ["FastAPI", "Pydantic v2", "vanilla JS"],
        },
        "files": files,
    }


# ----------------------------------------------------------------------------
# Blueprint: Chat
# ----------------------------------------------------------------------------
def blueprint_chat(prompt: str) -> dict:
    name = _name_from_prompt(prompt, "ChatApp")
    slug = _slug(name, "chat")
    server_py = _server_preamble(name) + '''
class Room(BaseModel):
    id: str = Field(default_factory=lambda: uuid.uuid4().hex)
    name: str
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

class Message(BaseModel):
    id: str = Field(default_factory=lambda: uuid.uuid4().hex)
    room_id: str
    author: str
    body: str
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

_db.setdefault("rooms", {})
_db.setdefault("messages", {})

def _bootstrap():
    if _db["rooms"]: return
    r = Room(name="lobby"); _db["rooms"][r.id] = r.model_dump()
_bootstrap()

@app.get("/api/rooms")
def list_rooms(): return list(_db["rooms"].values())

@app.post("/api/rooms")
def create_room(r: Room):
    _db["rooms"][r.id] = r.model_dump(); return r

@app.get("/api/rooms/{room_id}/messages")
def list_messages(room_id: str, since: Optional[str] = None):
    msgs = [m for m in _db["messages"].values() if m["room_id"] == room_id]
    if since:
        msgs = [m for m in msgs if m["created_at"] > since]
    return sorted(msgs, key=lambda m: m["created_at"])

@app.post("/api/rooms/{room_id}/messages")
def post_message(room_id: str, m: Message):
    if room_id not in _db["rooms"]: raise HTTPException(404, "room not found")
    m.room_id = room_id
    _db["messages"][m.id] = m.model_dump(); return m
''' + _server_footer()

    body = """
<div class="row" style="gap:16px;align-items:flex-start">
  <div style="flex:0 0 200px">
    <div class="row" style="margin-bottom:8px"><button id="new-room">+ room</button></div>
    <div id="rooms"></div>
  </div>
  <div style="flex:1;min-width:0">
    <h3 id="room-title" class="muted">select a room</h3>
    <div id="messages" class="card" style="height:50vh;overflow:auto"></div>
    <div class="row" style="margin-top:8px">
      <input id="author" placeholder="your name" style="max-width:160px">
      <input id="body" placeholder="message…" style="flex:1">
      <button id="send">send</button>
    </div>
  </div>
</div>
"""
    script = r"""
let ROOM = null;
let lastTs = "";

async function loadRooms() {
  const rooms = await fetch(API+"/api/rooms").then(r=>r.json());
  const root = document.getElementById("rooms"); root.innerHTML = "";
  for (const r of rooms) {
    const el = document.createElement("div");
    el.className = "card"; el.style.cursor = "pointer";
    el.textContent = "#" + r.name;
    el.onclick = () => openRoom(r);
    root.appendChild(el);
  }
}
async function openRoom(r) {
  ROOM = r; lastTs = "";
  document.getElementById("room-title").textContent = "#" + r.name;
  document.getElementById("messages").innerHTML = "";
  pollMessages();
}
async function pollMessages() {
  if (!ROOM) return;
  const url = lastTs
    ? `${API}/api/rooms/${ROOM.id}/messages?since=${encodeURIComponent(lastTs)}`
    : `${API}/api/rooms/${ROOM.id}/messages`;
  const msgs = await fetch(url).then(r=>r.json());
  const root = document.getElementById("messages");
  for (const m of msgs) {
    const el = document.createElement("div");
    el.innerHTML = `<strong style="color:var(--acc)">${m.author}</strong> <span class="muted" style="font-size:11px">${m.created_at.slice(11,19)}</span><div>${m.body}</div>`;
    el.style.marginBottom = "8px";
    root.appendChild(el);
    lastTs = m.created_at;
  }
  root.scrollTop = root.scrollHeight;
}
setInterval(pollMessages, 1500);

document.getElementById("new-room").onclick = async () => {
  const name = prompt("room name?");
  if (!name) return;
  await fetch(API+"/api/rooms", {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name})});
  loadRooms();
};
document.getElementById("send").onclick = async () => {
  if (!ROOM) return alert("select a room");
  const author = document.getElementById("author").value.trim() || "anon";
  const body = document.getElementById("body").value.trim();
  if (!body) return;
  await fetch(API+`/api/rooms/${ROOM.id}/messages`, {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({author,body,room_id:ROOM.id})});
  document.getElementById("body").value = ""; pollMessages();
};
loadRooms();
"""
    files = [
        {"path": "backend/server.py", "content": server_py},
        {"path": "backend/requirements.txt", "content": _requirements_txt()},
        {"path": "frontend/index.html", "content": _html(name, body, script)},
        {"path": "run.sh", "content": _run_sh()},
        {"path": "README.md", "content": _readme(name, "chat rooms with polling-based realtime", ["bash run.sh"])},
    ]
    return {
        "bot": {
            "name": f"{slug}.builder.v1",
            "domain": "chat",
            "recipe": [
                "detect-domain(chat)",
                "scaffold(fastapi+inmem)",
                "emit(Room,Message models)",
                "emit(polling endpoint via ?since=)",
                "compose(rooms sidebar + chat pane)",
            ],
            "templates": [f["path"] for f in files],
        },
        "app": {
            "name": name,
            "version": "0.1.0",
            "tagline": "chat rooms with polling-based realtime",
            "entities": [
                {"name":"Room","fields":[{"name":"id","type":"str"},{"name":"name","type":"str"}]},
                {"name":"Message","fields":[{"name":"id","type":"str"},{"name":"room_id","type":"str"},{"name":"author","type":"str"},{"name":"body","type":"str"},{"name":"created_at","type":"datetime"}]},
            ],
            "endpoints": [
                {"method":"GET","path":"/api/rooms","purpose":"list rooms"},
                {"method":"POST","path":"/api/rooms","purpose":"create room"},
                {"method":"GET","path":"/api/rooms/{id}/messages","purpose":"list messages (with ?since= poll)"},
                {"method":"POST","path":"/api/rooms/{id}/messages","purpose":"post message"},
            ],
            "stack": ["FastAPI", "Pydantic v2", "vanilla JS", "long-poll"],
        },
        "files": files,
    }


# ----------------------------------------------------------------------------
# Blueprint: Generic CRUD (fallback)
# ----------------------------------------------------------------------------
def blueprint_crud(prompt: str) -> dict:
    name = _name_from_prompt(prompt, "App")
    # try to extract a noun for the entity
    nouns = [w for w in re.findall(r"[a-zA-Z]+", prompt.lower()) if len(w) > 3]
    stop = {"that", "with", "this", "from", "into", "what", "have", "want", "need", "make", "build", "create"}
    entity = next((n for n in nouns if n not in stop), "item").capitalize()
    slug = _slug(name, "app")
    server_py = _server_preamble(name) + f'''
class {entity}(BaseModel):
    id: str = Field(default_factory=lambda: uuid.uuid4().hex)
    title: str
    body: str = ""
    done: bool = False
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

_db.setdefault("{entity.lower()}s", {{}})

@app.get("/api/{entity.lower()}s")
def list_items(): return list(_db["{entity.lower()}s"].values())

@app.post("/api/{entity.lower()}s")
def create(it: {entity}):
    _db["{entity.lower()}s"][it.id] = it.model_dump(); return it

@app.get("/api/{entity.lower()}s/{{item_id}}")
def get_item(item_id: str):
    if item_id not in _db["{entity.lower()}s"]: raise HTTPException(404, "{entity.lower()} not found")
    return _db["{entity.lower()}s"][item_id]

@app.patch("/api/{entity.lower()}s/{{item_id}}")
def update(item_id: str, it: {entity}):
    if item_id not in _db["{entity.lower()}s"]: raise HTTPException(404, "{entity.lower()} not found")
    data = it.model_dump(); data["id"] = item_id
    _db["{entity.lower()}s"][item_id] = data; return data

@app.delete("/api/{entity.lower()}s/{{item_id}}")
def delete(item_id: str):
    _db["{entity.lower()}s"].pop(item_id, None); return {{"ok": True}}
''' + _server_footer()

    body = f"""
<div class="row" style="margin-bottom:16px;gap:8px">
  <input id="t" placeholder="new {entity.lower()} title" style="max-width:320px">
  <button id="add">+ add</button>
</div>
<div id="list"></div>
"""
    script = f"""
const ENT = "{entity.lower()}s";
async function load() {{
  const items = await fetch(API+`/api/${{ENT}}`).then(r=>r.json());
  const list = document.getElementById("list"); list.innerHTML = "";
  if (!items.length) {{ list.innerHTML='<em class="muted">empty</em>'; return; }}
  for (const it of items) {{
    const el = document.createElement("div");
    el.className = "card";
    el.innerHTML = `<div class="row" style="justify-content:space-between"><strong>${{it.title}}</strong><div class="row"><button class="t">${{it.done?'✓ done':'mark done'}}</button><button class="d" style="border-color:#ff5555;color:#ff5555">delete</button></div></div>`;
    el.querySelector(".t").onclick = async ()=>{{ await fetch(API+`/api/${{ENT}}/${{it.id}}`,{{method:"PATCH",headers:{{"Content-Type":"application/json"}},body:JSON.stringify({{...it,done:!it.done}})}}); load();}};
    el.querySelector(".d").onclick = async ()=>{{ await fetch(API+`/api/${{ENT}}/${{it.id}}`,{{method:"DELETE"}}); load();}};
    document.getElementById("list").appendChild(el);
  }}
}}
document.getElementById("add").onclick = async ()=>{{
  const t = document.getElementById("t").value.trim();
  if (!t) return;
  await fetch(API+`/api/${{ENT}}`,{{method:"POST",headers:{{"Content-Type":"application/json"}},body:JSON.stringify({{title:t}})}});
  document.getElementById("t").value=""; load();
}};
load();
"""
    files = [
        {"path": "backend/server.py", "content": server_py},
        {"path": "backend/requirements.txt", "content": _requirements_txt()},
        {"path": "frontend/index.html", "content": _html(name, body, script)},
        {"path": "run.sh", "content": _run_sh()},
        {"path": "README.md", "content": _readme(name, f"{entity} CRUD app", ["bash run.sh"])},
    ]
    return {
        "bot": {
            "name": f"{slug}.builder.v1",
            "domain": "generic-crud",
            "recipe": [
                "detect-domain(generic-crud)",
                f"extract-entity({entity})",
                "scaffold(fastapi+inmem)",
                "emit(CRUD endpoints)",
                "compose(list+add UI)",
            ],
            "templates": [f["path"] for f in files],
        },
        "app": {
            "name": name,
            "version": "0.1.0",
            "tagline": f"{entity} CRUD",
            "entities": [
                {"name": entity, "fields":[{"name":"id","type":"str"},{"name":"title","type":"str"},{"name":"body","type":"str"},{"name":"done","type":"bool"}]},
            ],
            "endpoints": [
                {"method":"GET","path":f"/api/{entity.lower()}s","purpose":"list"},
                {"method":"POST","path":f"/api/{entity.lower()}s","purpose":"create"},
                {"method":"GET","path":f"/api/{entity.lower()}s/{{id}}","purpose":"read"},
                {"method":"PATCH","path":f"/api/{entity.lower()}s/{{id}}","purpose":"update"},
                {"method":"DELETE","path":f"/api/{entity.lower()}s/{{id}}","purpose":"delete"},
            ],
            "stack": ["FastAPI", "Pydantic v2", "vanilla JS"],
        },
        "files": files,
    }


# ----------------------------------------------------------------------------
# Dispatcher
# ----------------------------------------------------------------------------
BLUEPRINTS: dict[str, Callable[[str], dict]] = {
    "kanban": blueprint_kanban,
    "notes": blueprint_notes,
    "habit-tracker": blueprint_habits,
    "chat": blueprint_chat,
    "generic-crud": blueprint_crud,
}

_KEYWORDS = [
    ("kanban", ["kanban", "trello", "board", "task board", "swimlane", "card column", "drag and drop", "drag-and-drop"]),
    ("habit-tracker", ["habit", "streak", "tracker", "daily"]),
    ("chat", ["chat", "message", "messenger", "rooms", "dm ", "messaging"]),
    ("notes", ["note", "notes", "journal", "diary", "knowledge base", "wiki"]),
]


def detect_domain(prompt: str) -> str:
    p = " " + prompt.lower() + " "
    for domain, kws in _KEYWORDS:
        for kw in kws:
            if kw in p:
                return domain
    return "generic-crud"


def build_project(prompt: str, exemplars: list[dict] | None = None) -> dict:
    domain = detect_domain(prompt)
    fn = BLUEPRINTS[domain]
    proj = fn(prompt)
    proj["bot"]["dna_signature"] = "0x" + hashlib.md5((domain + prompt).encode()).hexdigest()[:8]
    if exemplars:
        top = exemplars[0]
        proj["bot"]["inherited_from"] = top.get("id")
    return proj


def critique_files(proj: dict) -> str:
    files = proj.get("files", [])
    total_lines = sum(len(f["content"].splitlines()) for f in files)
    eps = proj.get("app", {}).get("endpoints", [])
    notes = []
    if not any(f["path"].startswith("backend/") for f in files):
        notes.append("missing backend/ files — project will not run")
    if not any(f["path"] == "run.sh" for f in files):
        notes.append("no run.sh — onboarding will be painful")
    if not any(f["path"] == "README.md" for f in files):
        notes.append("no README — new contributors are lost")
    if total_lines < 100:
        notes.append(f"only {total_lines} lines of code — shape feels skeletal")
    if not any(ep.get("method") == "DELETE" for ep in eps):
        notes.append("no DELETE endpoint — destructive ops can't be undone via UI")
    if proj.get("bot", {}).get("domain") == "generic-crud":
        notes.append("fell back to generic CRUD — prompt may need clearer domain words")
    if not notes:
        notes = [
            f"{len(files)} files, {total_lines} loc — runnable footprint looks sound",
            f"{len(eps)} endpoints wired to the produced entities — good coverage",
            "consider swapping the in-memory dict for MongoDB before deploying",
        ]
    return " // ".join(notes[:3])


def rate_files(proj: dict) -> dict:
    files = proj.get("files", [])
    total_lines = sum(len(f["content"].splitlines()) for f in files)
    eps = proj.get("app", {}).get("endpoints", [])
    ents = proj.get("app", {}).get("entities", [])
    methods = {ep.get("method") for ep in eps}

    helpfulness = min(3.5, 1.0 + 0.4 * len(files))                 # more files → more helpful
    correctness = min(3.5, 0.8 + 0.3 * len(eps))                   # more endpoints wired
    coherence = 2.0 + (1.0 if {"GET", "POST"}.issubset(methods) else 0)
    coherence += 0.5 if {"PATCH", "DELETE"}.issubset(methods) else 0
    coherence = min(3.8, coherence)
    complexity = min(2.5, 0.5 + 0.2 * len(ents))
    verbosity = max(0.5, min(2.5, total_lines / 200.0))
    return {
        "helpfulness": round(helpfulness, 2),
        "correctness": round(correctness, 2),
        "coherence": round(coherence, 2),
        "complexity": round(complexity, 2),
        "verbosity": round(verbosity, 2),
    }
